# Generated by Django 6.0.5 on 2026-06-04 21:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Direccion',
            new_name='Adress',
        ),
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Pedido',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='DetallePedido',
            new_name='orderDetail',
        ),
        migrations.RenameModel(
            old_name='Producto',
            new_name='Product',
        ),
    ]
