# Generated by Django 6.0.5 on 2026-07-01 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0002_rename_direccion_adress_rename_categoria_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ecomerce.order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='ecomerce.category'),
        ),
    ]
