# Generated by Django 6.0.5 on 2026-07-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0003_alter_orderdetail_pedido_alter_product_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagen',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
