# Generated by Django 6.0.5 on 2026-07-14 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0005_rename_adress_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='ecomerce.address'),
        ),
    ]
