# Generated by Django 6.0.5 on 2026-07-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='metodo_pago',
            field=models.CharField(choices=[('credito', 'Crédito'), ('paypal', 'PayPal')], default='credito', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
    ]
